---
- name: Apr install on CentOS 7
  hosts: dmz-web1
  become: true
  gather_facts: no
  tasks:
    - name: download
      get_url:
        url: https://downloads.apache.org//apr/apr-1.7.0.tar.gz
        dest: /usr/local/src/apr-1.7.0.tar.gz
        mode: '0755'

    - name: APR 1.7.0 설치
      shell: |
        cd /usr/local/src
        tar xvfz apr-1.7.0.tar.gz
        rm -rf /usr/local/src/apr-1.7.0.tar.gz
        cd /usr/local/src/apr-1.7.0
        ./configure  --prefix=/usr/local/apr
        make && make install

    - name: 설치확인
      shell: |
        /usr/local/apr/bin/apr-1-config --version
      register: output
    - debug: msg="{{ output.stdout_lines }}"