---
- name: Remove old openssl
  hosts: dmz-web1
  become: true
  gather_facts: no
  tasks:
    - name: before openssl version
      shell: openssl version
      register: output
    - debug: msg="{{ output.stdout }}"

    - name: before openssl 지원 프로토콜 확인
      shell: openssl ciphers -v | awk '{print $2}' | sort | uniq
      register: output
    - debug: msg="{{ output.stdout_lines }}"

    - name: yum remove openssl
      shell: yum remove -y openssl