Vagrant.configure("2") do |config|
    config.vm.box = "centos_openssl/7"
    config.vm.box_check_update = true

    config.vm.network "public_network", auto_config: false,  bridge: "dmz"
    config.vm.hostname = "dzm-web1"


    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.boot_timeout = 60

    config.vm.provider "hyperv" do |vb|
        vb.auto_start_action= "StartIfRunning"
        vb.auto_stop_action = "TurnOff"
        vb.cpus = 1
        vb.memory = 1024*2
        vb.vmname = "dzm-web1"
    end

    config.vm.provision "shell", inline: <<-SHELL
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config

        # ssh restart
        systemctl restart sshd

        # static network set
        /vagrant/scripts/configure-static-ip.sh

        # 종료시키기
        shutdown -r now
    SHELL
end
